Add null provider to support the privacy API
openequella/moodle-block_openEQUELLA_search pull request #7
Opened 2020-08-26 02:28 UTC by SammyIsConfused

Moodle now adheres to the GDPR which means we need to implement a privacy provider. 
See https://docs.moodle.org/dev/Privacy_API#Plugins_which_do_not_store_personal_data for details.  

![image](https://user-images.githubusercontent.com/24543345/91247543-d7823700-e795-11ea-8da0-036e3d89578a.png)

2020-08-26 02:30 UTC, ChristianMurphy commented on classes/privacy/provider.php
> +}
```suggestion
}

```

2020-08-26 02:30 UTC, ChristianMurphy commented on classes/privacy/provider.php
> +    //this plugin does not store any personal user data.
```suggestion
    // this plugin does not store any personal user data.
```

2020-08-26 03:48 UTC, edalex-ian requested changes
Seems fine, just need to make sure we close those php tags. (You may even want to consider doing the same for the other files in this repo.)

Also, same query about the text: https://github.com/openequella/moodle-block_openEQUELLA_links/pull/7#discussion_r477014178

2020-08-26 04:58 UTC, ChristianMurphy commented
> just need to make sure we close those php tags

PSR-2, the PHP code style, recommends never adding `?>` to pure PHP files.
https://www.php-fig.org/psr/psr-2/#22-files

2020-08-26 05:01 UTC, edalex-ian commented
No probs. https://github.com/openequella/moodle-block_openEQUELLA_tasks/pull/5#discussion_r477034544

2020-08-27 05:16 UTC, edalex-ian approved these changes

2020-08-31 03:16 UTC, merged